global function FireCommand_Init


void function FireCommand_Init()
{
    ServerChatCommand_Admin_Init()
    ServerChatCommand_Cheats_Init()
    ServerChatCommand_Team_Init()
    ServerChatCommand_Pl_Init()
    ServerChatCommand_Uid_Init()
    ServerChatCommand_Ban_Init()
    ServerChatCommand_Kick_Init()
    ServerChatCommand_Chat_Init()
    ServerChatCommand_Stop_Init()
    ServerChatCommand_Ajb_Init()
    ServerChatCommand_Mute_Init()
    ServerChatCommand_Aa_Init()
    ServerChatCommand_Map_Init()
    if( !IsLobby() && !IsMenuLevel() )
    {
        ServerChatCommand_Core_Init()
        ServerChatCommand_Tp_Init()
        ServerChatCommand_Fold_Init()
        ServerChatCommand_God_Init()
        ServerChatCommand_Hp_Init()
        ServerChatCommand_Mhp_Init()
        ServerChatCommand_Kill_Init()
        ServerChatCommand_Cb_Init()
        ServerChatCommand_Noclip_Init()
        ServerChatCommand_Hide_Init()
        ServerChatCommand_Show_Init()
        ServerChatCommand_Tf_Init()
        ServerChatCommand_Man_Init()
        ServerChatCommand_Skip_Init()
        ServerChatCommand_Afk_Init()
        ServerChatCommand_Fly_Init()
        ServerChatCommand_Bal_Init()
        ServerChatCommand_Ogre_Init()
        ServerChatCommand_Ring_Init()
        ServerChatCommand_Give_Init()
        ServerChatCommand_Rf_Init()
        ServerChatCommand_Danmaku_Init()
        ServerChatCommand_Csb_Init()
        ServerChatCommand_Hack_Init()
        ServerChatCommand_Eject_Init()
    }
}