global function FireCommand_Init


void function FireCommand_Init()
{
    ConsoleCommand_Fire_Init()
    ChatCommand_Admin_Init()
    ChatCommand_Cheats_Init()
    ChatCommand_Team_Init()
    ChatCommand_Pl_Init()
    ChatCommand_Uid_Init()
    ChatCommand_Ban_Init()
    ChatCommand_Kick_Init()
    ChatCommand_Chat_Init()
    ChatCommand_Stop_Init()
    ChatCommand_Ajb_Init()
    ChatCommand_Mute_Init()
    ChatCommand_Aa_Init()
    ChatCommand_Map_Init()
    ChatCommand_Csb_Init()
    ChatCommand_Reload_Init()
    ChatCommand_Script_Init()
    if( !IsFFAGame() )
    {
        ChatCommand_Switch_Init()
    }
    if( GameRules_GetGameMode() == FD )
    {
        ChatCommand_Money_Init()
        ChatCommand_Reserve_Init()
    }
    if( !IsLobby() && !IsMenuLevel() )
    {
        ChatCommand_SpacebasedCannon_Init()
        ChatCommand_Core_Init()
        ChatCommand_Tp_Init()
        ChatCommand_Fold_Init()
        ChatCommand_God_Init()
        ChatCommand_Hp_Init()
        ChatCommand_Mhp_Init()
        ChatCommand_Kill_Init()
        ChatCommand_Cb_Init()
        ChatCommand_Noclip_Init()
        ChatCommand_Hide_Init()
        ChatCommand_Show_Init()
        ChatCommand_Tf_Init()
        ChatCommand_Man_Init()
        ChatCommand_Skip_Init()
        ChatCommand_Afk_Init()
        ChatCommand_Fly_Init()
        ChatCommand_Bal_Init()
        ChatCommand_Ogre_Init()
        ChatCommand_Ring_Init()
        ChatCommand_Give_Init()
        ChatCommand_Rf_Init()
        ChatCommand_Danmaku_Init()
        ChatCommand_Hack_Init()
        ChatCommand_Eject_Init()
    }
}